apiVersion: v2
appVersion: 0.12.4
annotations:
  category: app
  licenses: MIT
  "artifacthub.io/license": MIT
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/dougEfresh/celestia-helm-chart
dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 2.x.x
description: Celestia node application
home: https://celestia.org
icon: https://s2.coinmarketcap.com/static/img/coins/128x128/22861.png
name: celestia-node
version: 0.1.5
maintainers:
  - name: dougefresh
    email: dchimento@gmail.com
sources:
  - https://github.com/dougEfresh/celestia-helm-chart
keywords:
  - crypto
  - blockchain
  - celestia
